[theme]
primaryColor = "#ff0000"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true
staticFolder = "assets"

[browser]
gatherUsageStats = false
